### ISSUE TITLE
Cant install npm install angular-svg-round-progressbar@1.1.1 --save

### ISSUE THREAD

**Issue by AltRoot17** [Sampath-Lokuge/svgapp#1]
Sir
Im try to install for this Ionic 3, Its not work for me

D:\Mobile Application\Ionic\myApp>npm install angular-svg-round-progressbar@1.1.1 --save
npm ERR! path D:\Mobile Application\Ionic\myApp\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'D:\Mobile Application\Ionic\myApp\node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'D:\Mobile Application\Ionic\myApp\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\Mobile Application\\Ionic\\myApp\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'D:\\Mobile Application\\Ionic\\myApp\\node_modules\\fsevents\\node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hp Probook\AppData\Roaming\npm-cache\_logs\2017-11-09T09_40_58_868Z-debug.log

**Comment by Sampath-Lokuge** [comment]
Can you clone this project and run it?

**Comment by AltRoot17** [comment]
yes sir,previous error is  fixed, but  not work progress bar,  displayed following error 
```
Runtime Error
Unexpected value 'RoundProgressService' imported by the module 'AppModule'. Please add a @NgModule annotation.
```

**Comment by Sampath-Lokuge** [comment]
Are you telling about this project or your one?

**Comment by AltRoot17** [comment]
Sir im recreated this type project

**Comment by Sampath-Lokuge** [comment]
Can you upload it to the public git repo and tell me the url?

**Comment by AltRoot17** [comment]
ok  sure sir

**Comment by AltRoot17** [comment]
Sir look at this , https://github.com/AltRoot17/myApp

**Comment by Sampath-Lokuge** [comment]
Ok sure.

**Comment by AltRoot17** [comment]
Thanks sir

**Comment by Sampath-Lokuge** [comment]
Hope this is related to this question no? https://stackoverflow.com/questions/47067969/angular-svg-round-progressbar-not-work-for-ionic

**Comment by AltRoot17** [comment]
Sir,  It's open me,  still no t fix my issue

**Comment by Sampath-Lokuge** [comment]
The problem here is this module is not compatible with Angular 5 yet. You need to use Angular `4.4.4` with Ionic `3.8.0`. If you clone my project then it should work.

**Comment by AltRoot17** [comment]
Ok, sir I'll clone your project

**Comment by AltRoot17** [comment]
sir , I'm clone your project , ```
Runtime Error
Uncaught (in promise): Error: Unexpected value 'RoundProgressModule' imported by the module 'HomePageModule'. Please add a @NgModule annotation. Error: Unexpected value 'RoundProgressModule' imported by the module 'HomePageModule'. Please add a @NgModule annotation. at syntaxError (http://localhost:8100/build/vendor.js:78267:34) at http://localhost:8100/build/vendor.js:92120:44 at Array.forEach (<anonymous>) at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:92103:49) at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:103538:70) at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:103511:36) at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:103440:37) at ModuleBoundCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:103840:31) at http://localhost:8100/build/vendor.js:66692:25 at t.invoke (http://localhost:8100/build/polyfills.js:3:14356)
```

**Comment by AltRoot17** [comment]
package.json

```
"dependencies": {
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.0.1",
    "angular-svg-round-progressbar": "^1.1.1",
    "ionic-angular": "3.8.0",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
```

**Comment by Sampath-Lokuge** [comment]
Can you show `ionic info`?

**Comment by AltRoot17** [comment]
```
{
  "name": "SvgApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/compiler-cli": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@ionic-native/core": "4.3.2",
    "@ionic-native/splash-screen": "4.3.2",
    "@ionic-native/status-bar": "4.3.2",
    "@ionic/storage": "2.0.1",
    "angular-svg-round-progressbar": "^1.1.1",
    "ionic-angular": "3.8.0",
    "ionicons": "3.0.0",
    "rxjs": "5.4.3",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.0.1",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project"
}
```

**Comment by Sampath-Lokuge** [comment]
NO. Run `ionic info` as CLI on your project.

**Comment by AltRoot17** [comment]
My ionic version is`  3.17.0`

**Comment by AltRoot17** [comment]
cli packages: (C:\Users\Hp Probook\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

local packages:

    @ionic/app-scripts : 3.0.1
    Ionic Framework    : ionic-angular 3.8.0

System:

    Node : v8.8.0
    npm  : 5.3.0
    OS   : Windows 10

Misc:

    backend : pro

**Comment by Sampath-Lokuge** [comment]
Working now. Get the latest from this repo and delete `node_modules` folder and after that run `npm i`

**Comment by Sampath-Lokuge** [comment]
Hope now you can close the StackOverflow question too.
